
USE DB_MYSQL;

CREATE TABLE IF NOT EXISTS TABLE_MYSQL (
  id INT AUTO_INCREMENT NOT NULL primary key,
  name VARCHAR(255) NULL,
  created_at DATETIME NOT NULL DEFAULT NOW(),
  updated_at DATETIME NULL,
  deleted_at DATETIME NULL
);

stop SLAVE;
CHANGE MASTER TO MASTER_HOST='172.100.0.3', MASTER_USER='slave_user', MASTER_PASSWORD='slave_pass', MASTER_LOG_FILE='mysql-bin.000001', MASTER_LOG_POS=107;
START SLAVE;

SHOW SLAVE STATUS;
SET GLOBAL SQL_SLAVE_SKIP_COUNTER = 1;
